---

- name: Create a {{ application_name }} local environment
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    - setup_git_repo: no
    - setup_cron_jobs: no
    - update_apt_cache: yes
  vars_files:
    - env_vars/local.yml

  roles:
    - base
    - db
    - web